# Generated by Django 4.2 on 2023-08-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='is_active',
            new_name='active',
        ),
        migrations.AddField(
            model_name='video',
            name='published_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='state',
            field=models.CharField(choices=[('DR', 'Draft'), ('PU', 'Publish')], default='DR', max_length=200),
        ),
    ]
